// Generated by gencpp from file object_segmentation/AddTwoInts.msg
// DO NOT EDIT!


#ifndef OBJECT_SEGMENTATION_MESSAGE_ADDTWOINTS_H
#define OBJECT_SEGMENTATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <object_segmentation/AddTwoIntsRequest.h>
#include <object_segmentation/AddTwoIntsResponse.h>


namespace object_segmentation
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace object_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_segmentation::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::object_segmentation::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::object_segmentation::AddTwoInts > {
  static const char* value()
  {
    return "object_segmentation/AddTwoInts";
  }

  static const char* value(const ::object_segmentation::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::object_segmentation::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::object_segmentation::AddTwoInts > 
template<>
struct MD5Sum< ::object_segmentation::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_segmentation::AddTwoInts >::value();
  }
  static const char* value(const ::object_segmentation::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_segmentation::AddTwoIntsRequest> should match 
// service_traits::DataType< ::object_segmentation::AddTwoInts > 
template<>
struct DataType< ::object_segmentation::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::object_segmentation::AddTwoInts >::value();
  }
  static const char* value(const ::object_segmentation::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_segmentation::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::object_segmentation::AddTwoInts > 
template<>
struct MD5Sum< ::object_segmentation::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_segmentation::AddTwoInts >::value();
  }
  static const char* value(const ::object_segmentation::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_segmentation::AddTwoIntsResponse> should match 
// service_traits::DataType< ::object_segmentation::AddTwoInts > 
template<>
struct DataType< ::object_segmentation::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::object_segmentation::AddTwoInts >::value();
  }
  static const char* value(const ::object_segmentation::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_SEGMENTATION_MESSAGE_ADDTWOINTS_H
